#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "c_except.h"


double read_double() {
    char buf[20];
    char *end;
    double val;

    fgets(buf, sizeof(buf), stdin);
    val = strtod(buf, &end);
    if (end == buf)
        THROW(NUMBER_PARSE_ERROR);

    return val;
}


double divide(double a, double b) {
    if (b == 0)
        THROW(DIVIDE_BY_ZERO);

    return a / b;
}


int main() {
    double n1, n2;

    printf("Tell me two numbers, and I will tell you their quotient!\n");


    {
        jmp_buf env;
        int exception = setjmp(env);
        if (exception == NO_EXCEPTION) {
            start_try(&env);
            /* Pushes the jmp_buf, for nested try/catch. */
            {
                printf("Enter your first number, the dividend: ");
                n1 = read_double();
                printf("Now enter your second number, the divisor: ");
                n2 = read_double();
                printf("The quotient of %lg / %lg is: %lg \
                        n", n1, n2, divide(n1, n2));
            }
            finish_try();
            /* Pops the jmp_buf, for nested try/catch. */
        }
        else if (exception == NUMBER_PARSE_ERROR) {
            printf("Ack!! I couldn't parse what you entered! \n");
            throw_exception(exception);
            /* Generated by RETHROW macro. */
        }
        else if (exception == DIVIDE_BY_ZERO) {
            printf("Ack!! You entered 0 for the divisor! \n");
        }
        else {
            /* Exception wasn't handled by any catch
               -
               block.
             * Propagate to the next enclosing try/catch block.
             */
            throw_exception(exception);
        }
    };

    return 0;
}

